name: CImain

on:
  pull_request:
    branches: [ Tests+CI ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Running unit tests
        run: ./gradlew app:test
